apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  mongoDbUrl: "mongodb+srv://safiaadel:6gQAJfcnSVz7KsYD@cluster0.zta02aa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
